import { MaturityLevel } from './scoring';
import type { MaturityRecommendations } from './recommendations';

export const RECOMMENDATIONS_BY_LEVEL_EN: Record<MaturityLevel, MaturityRecommendations> = {
  'Explorer': {
    level: 'Explorer',
    characteristics: [
      'No formal AI initiative',
      'Fragmented data',
      'No AI skills',
      'Traditional culture',
    ],
    topRecommendations: [
      {
        title: 'Define an AI vision aligned with business strategy',
        description: 'Run a workshop with leadership to define a clear AI vision and its role in company strategy.',
        impact: 'High',
        effort: 'Low',
        timeline: '2-4 weeks',
        dimension: 'strategy',
      },
      {
        title: 'Identify 2-3 quick-win use cases',
        description: 'Identify simple AI use cases with fast ROI (e.g. task automation, customer chatbot).',
        impact: 'High',
        effort: 'Low',
        timeline: '1-2 weeks',
        dimension: 'strategy',
      },
      {
        title: 'Train leadership on AI opportunities',
        description: 'Run a one-day executive session on AI opportunities, use cases, and return on investment.',
        impact: 'High',
        effort: 'Low',
        timeline: '1 day',
        dimension: 'strategy',
      },
      {
        title: 'Audit data quality and availability',
        description: 'Conduct a full audit of your data: quality, accessibility, governance, and AI readiness.',
        impact: 'High',
        effort: 'Medium',
        timeline: '2-3 weeks',
        dimension: 'data',
      },
      {
        title: 'Engage an AI partner for roadmap',
        description: 'Work with an expert partner to create an AI roadmap tailored to your context and goals.',
        impact: 'High',
        effort: 'Low',
        timeline: '2-4 weeks',
        dimension: 'strategy',
      },
    ],
    nextSteps: [
      { title: 'AI vision workshop', duration: '1 day' },
      { title: 'Data assessment', duration: '2-3 weeks' },
      { title: 'Executive training', duration: '1 day' },
    ],
  },
  'Experimenter': {
    level: 'Experimenter',
    characteristics: [
      'Pilot projects underway',
      'Partially structured data',
      '1-2 people with AI skills',
      'Growing interest',
    ],
    topRecommendations: [
      {
        title: 'Prioritize 1 pilot for production',
        description: 'Select the most promising pilot and turn it into a production solution with monitoring and governance.',
        impact: 'High',
        effort: 'Medium',
        timeline: '2-3 months',
        dimension: 'technology',
      },
      {
        title: 'Invest in modern data infrastructure',
        description: 'Migrate to a modern cloud infrastructure (data warehouse/lake) to support AI initiatives.',
        impact: 'High',
        effort: 'High',
        timeline: '3-6 months',
        dimension: 'data',
      },
      {
        title: 'Hire or train data scientists',
        description: 'Build a small data science team (2-3 people) through hiring or internal training.',
        impact: 'High',
        effort: 'Medium',
        timeline: '2-4 months',
        dimension: 'talent',
      },
      {
        title: 'Establish basic AI governance',
        description: 'Put in place an AI governance framework with a steering committee and basic guidelines.',
        impact: 'Medium',
        effort: 'Low',
        timeline: '1-2 months',
        dimension: 'governance',
      },
      {
        title: 'Build a solid ROI business case',
        description: 'Develop a strong business case with quantified ROI to secure budget for AI initiatives.',
        impact: 'High',
        effort: 'Medium',
        timeline: '2-3 weeks',
        dimension: 'strategy',
      },
    ],
    nextSteps: [
      { title: 'POC to production roadmap', duration: '2-3 months' },
      { title: 'Cloud infrastructure migration', duration: '3-6 months' },
      { title: 'Data scientist recruitment', duration: '2-4 months' },
    ],
  },
  'Adopter': {
    level: 'Adopter',
    characteristics: [
      '1-2 AI solutions in production',
      'Established cloud infrastructure',
      'Data science team in place',
      'Basic MLOps processes',
    ],
    topRecommendations: [
      {
        title: 'Industrialize AI deployment (MLOps)',
        description: 'Implement a full MLOps platform to automate deployment, monitoring, and model retraining.',
        impact: 'High',
        effort: 'High',
        timeline: '3-6 months',
        dimension: 'governance',
      },
      {
        title: 'Extend use cases to other departments',
        description: 'Identify and deploy AI use cases in other departments (HR, finance, operations).',
        impact: 'High',
        effort: 'Medium',
        timeline: '4-6 months',
        dimension: 'strategy',
      },
      {
        title: 'Create an AI center of excellence',
        description: 'Establish an AI center of excellence to centralize skills, best practices, and governance.',
        impact: 'High',
        effort: 'Medium',
        timeline: '3-4 months',
        dimension: 'talent',
      },
      {
        title: 'Implement governance framework',
        description: 'Develop a full AI governance framework with review processes, compliance, and audit.',
        impact: 'Medium',
        effort: 'Medium',
        timeline: '2-3 months',
        dimension: 'governance',
      },
      {
        title: 'Measure and communicate ROI',
        description: 'Put in place ROI measurement for AI initiatives and communicate results internally and externally.',
        impact: 'Medium',
        effort: 'Low',
        timeline: '1-2 months',
        dimension: 'culture',
      },
    ],
    nextSteps: [
      { title: 'MLOps platform setup', duration: '3-6 months' },
      { title: 'AI center of excellence', duration: '3-4 months' },
      { title: 'Governance framework', duration: '2-3 months' },
    ],
  },
  'Integrator': {
    level: 'Integrator',
    characteristics: [
      '3-5 AI solutions in production',
      'Mature data platform',
      'Multidisciplinary AI team',
      'Established governance',
    ],
    topRecommendations: [
      {
        title: 'Develop proprietary AI capabilities',
        description: 'Invest in building proprietary AI models tailored to your specific business domain.',
        impact: 'High',
        effort: 'High',
        timeline: '6-12 months',
        dimension: 'technology',
      },
      {
        title: 'Implement GenAI at scale',
        description: 'Deploy an enterprise GenAI platform with fine-tuning, RAG, and governance across departments.',
        impact: 'High',
        effort: 'High',
        timeline: '6-9 months',
        dimension: 'technology',
      },
      {
        title: 'Create an internal AI academy',
        description: 'Set up an internal AI academy to train all employees and build an AI innovation culture.',
        impact: 'High',
        effort: 'Medium',
        timeline: '3-4 months',
        dimension: 'talent',
      },
      {
        title: 'Establish strategic partnerships',
        description: 'Develop partnerships with vendors, universities, and startups for co-innovation.',
        impact: 'Medium',
        effort: 'Low',
        timeline: '2-3 months',
        dimension: 'talent',
      },
      {
        title: 'Innovate with advanced AI (agents, multimodal)',
        description: 'Experiment with advanced AI such as autonomous agents and multimodal AI.',
        impact: 'High',
        effort: 'High',
        timeline: '6-12 months',
        dimension: 'technology',
      },
    ],
    nextSteps: [
      { title: 'GenAI platform deployment', duration: '6-9 months' },
      { title: 'Internal AI academy', duration: '3-4 months' },
      { title: 'Agentic AI pilots', duration: '6-12 months' },
    ],
  },
  'AI Leader': {
    level: 'AI Leader',
    characteristics: [
      '5+ AI solutions in production',
      'AI-native architecture',
      'Mature center of excellence',
      'Innovation culture',
    ],
    topRecommendations: [
      {
        title: 'Share your expertise (thought leadership)',
        description: 'Become an AI thought leader by sharing your experience through blogs, conferences, and case studies.',
        impact: 'Medium',
        effort: 'Low',
        timeline: 'Ongoing',
        dimension: 'culture',
      },
      {
        title: 'Monetize AI capabilities (AI-as-a-Service)',
        description: 'Turn your AI capabilities into products or services for other organizations.',
        impact: 'High',
        effort: 'High',
        timeline: '6-12 months',
        dimension: 'strategy',
      },
      {
        title: 'Invest in advanced AI R&D',
        description: 'Create an R&D lab to explore next-generation AI and stay at the forefront.',
        impact: 'High',
        effort: 'High',
        timeline: 'Ongoing',
        dimension: 'technology',
      },
      {
        title: 'Contribute to the AI ecosystem',
        description: 'Contribute to the AI ecosystem through open source, academic partnerships, and community initiatives.',
        impact: 'Medium',
        effort: 'Medium',
        timeline: 'Ongoing',
        dimension: 'culture',
      },
      {
        title: 'Continuously optimize with next-gen AI',
        description: 'Adopt new AI technologies (GPT-5, autonomous agents, etc.) quickly to keep optimizing.',
        impact: 'High',
        effort: 'Medium',
        timeline: 'Ongoing',
        dimension: 'technology',
      },
    ],
    nextSteps: [
      { title: 'Thought leadership strategy', duration: 'Ongoing' },
      { title: 'AI-as-a-Service business model', duration: '6-12 months' },
      { title: 'R&D partnerships', duration: 'Ongoing' },
    ],
  },
};
